### PR TITLE
Tooltip fixed for the mobile

### PR DESCRIPTION
**Pull request by adityadipankar**

### CODE REVIEW

**Comment by planemad** [comment]
@adityadipankar 
screenshot 2016-08-18 13 21 40

Looking great 👍 . Should the order be education - assets - cases to match the order in the header?

**Comment by adityadipankar** [comment]
Makes sense. Will update.

**Comment by adityadipankar** [comment]
So, the order (both in the header and the tooltip) would be:
1. Criminal Cases
2. Education
3. Assets?

Also, does this affect the ordering of the layers on the map? (I think yes)

**Comment by planemad** [comment]
@adityadipankar map layers are rendered in the same order as defined here https://github.com/folography/netafilter/blob/gh-pages/js/index.js#L18-L94

**Pull request merged**
